### ISSUE TITLE
Unblock saltwood.top

### ISSUE THREAD

**Issue by SALTWOOD** [entropi-hk/surge-rule-sets#1]
I’m the owner of the domain saltwood.top, and I recently noticed it’s been added to an ad block blacklist. I believe this happened because I ran a BT tracker on it in the past. At the time, I didn’t realize the potential issues this could cause.

As soon as I became aware of the problem, I removed the BT tracker completely from my domain. I’d like to confirm that it’s no longer being used for anything related to that.

Could you please review my domain and consider removing it from the blacklist? Let me know if you need any more details from me.

Thanks a lot for your help! Let me know immediately if you need any more information or have concerns.

I’m not fluent in English and used AI to assist with this issue. Please excuse any errors in grammar or wording.

**Comment by SALTWOOD** [comment]
It's my only personal domain, and it was originally used for hosting open-source programs. The BT tracker server that ran on the domain was used for researching principles, and after completing my research, I **unfortunately** didn’t turn it off in time.
So I turned it off and `rm -rf bt-tracker` **just now**.

**Comment by ainsly** [comment]
Hey @SALTWOOD! If I was in control of these blocklists I'd happily remove you, however this repo just takes the ready-made blocklists from hagezi and oisd and reformats them to a syntax that the Surge app can understand.

That being said, these lists are constantly updated, so the lists hosted here get updated on a daily basis to reflect those changes.

And GOOD NEWS for you, I can see that the domain you mentioned is no longer on any of the blocklists listed here.

I did a quick search through and I can see that it WAS listed in the hagezi anti-piracy blocklist, however it was [removed 2 days ago](https://github.com/entropi-hk/surge-rule-sets/commit/30d0aabbf26fc343c72c4c8750098fd9cd5d931c#diff-9dc5e8af474b71504827be5e2d422dcaf0c367548da8787eb97bdc97ca5e1903L7182)

So, whatever you did worked, looks like your domain is in the clear! 🥳 

But just to reiterate, I'm not responsible for the content of the lists themselves, so can't alter them without them just getting updated again the day after. So either you reached out to the right parties, or whatever vetting process hagezi and his sources have going on automatically removed your domain.

And no need to explain yourself, these things happen, and I believe people shouldn't be punished for research and a little experimenting; but you clearly quickly identified and rectified the problem, so good going 👍
